[boards]

[[boards.blackgold]]
name = "blackgold"
username = "username"
password = ""
login = "https://ab07.atrieveerp.com/blackgold/public/ExternalLogin.aspx"
jobboard = "https://ab07.atrieveerp.com/blackgold/servlet/Broker?env=ads&template=ads.JobShop1.xml"

[[boards.parkland]]
name = "parkland"
username = "username"
password = ""
login = "https://ab07.atrieveerp.com/parkland/public/ExternalLogin.aspx"
jobboard = "https://ab07.atrieveerp.com/parkland/servlet/Broker?env=ads&template=ads.JobShop1.xml"

[email]
emailto = "youremail@gmail.com"
emailcc = "someother_email@email.com"
emailfrom = "throw_away_email@gmail.com"
password = "app_password"
mobile_number = "5551234567@msg.telus.com"
smtp_server = "smtp.gmail.com"  # Replace with your email provider's SMTP server
smtp_port = "587"  # Replace with your email provider's SMTP port
